import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { NavBar } from "@/components/Layout/NavBar";
import { UIProvider } from "@/store/ui";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-primary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="pt-12">
        <Providers>
          <UIProvider>
            <NavBar />
            <main className="flex grow flex-col desktop:pl-72">{children}</main>
          </UIProvider>
        </Providers>
      </body>
    </html>
  );
}
