import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";
import { ModalRender } from "@/components/Modals/ModalRender";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-primary",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Defines the root layout for the Next.js application, applying global styles, font, and context providers.
 *
 * Wraps all page content with the Inter font, global providers, and a modal rendering component.
 *
 * @param children - The page content to be rendered within the layout.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} `}>
        <Providers>
          <ModalRender />
          {children}
        </Providers>
      </body>
    </html>
  );
}
